Optimisations
rhubarbgroup/redis-cache pull request #340
Opened 2022-02-19 16:11 UTC by colinleroy

Hello,

I hope you'll consider this PR. It aims at shaving a bit of performance (about 30% in redis-cache on my homepage) with two modifications:
- Avoid walking full arrays to determine group type: We use an associative array to get the type of the group instead of walking an array.
- Avoid sanitizing key/group multiple times in the same codepath: for example, ->get() was using sanitize_key to build the key and to check if the group was global.

I'll attach screenshots of KCachegrind that demonstrate the changes.

Hope this helps,
Colin

2022-02-19 16:12 UTC, colinleroy commented
Here is the call graph on WP_Object_Cache->get() before:
![image](https://user-images.githubusercontent.com/1016317/154808975-db498ce2-121b-4668-87cc-dc989f5bd650.png)

Here it is after:
![image](https://user-images.githubusercontent.com/1016317/154808988-c52a4220-a0be-43db-acd7-bb2701525891.png)

2022-02-19 16:14 UTC, colinleroy commented
Here is the total time passed in WP_Object_Cache functions before:
![image](https://user-images.githubusercontent.com/1016317/154809005-23fdd787-c300-4cc9-a79e-0c944d972073.png)

Here it is after:
![image](https://user-images.githubusercontent.com/1016317/154809018-f4e5c74e-ddf5-499b-b680-9e811d06ef0b.png)

You can see an improvement of about 19%.

2022-02-19 22:51 UTC, tillkruss requested changes

2022-02-19 22:51 UTC, tillkruss commented on includes/object-cache.php
> +        if ( ! $this->is_group_of_type( $san_group, "ignored" ) && $this->redis_status() ) {
For readability, let's keep `is_ignored_group()` and  `is_global_group()`.

2022-02-20 08:28 UTC, colinleroy commented
Hi @tillkruss ,
Thank you for your feedback. I've addressed your comment.
I also added a part in diagnostics to check on that array, and added refreshing the group type cache in case someone calls add_..._groups().

2022-02-23 16:29 UTC, colinleroy commented
Hi @tillkruss! Do you need me to fix something else on this PR?
Thanks :)
Colin

2022-02-24 16:53 UTC, tillkruss commented
@colinleroy: I have to review the changes in detail to make sure nothing breaks, otherwise 100,000 sites break.

2022-02-24 16:56 UTC, colinleroy commented
Ah, yes, understandably :)
Thanks !

2022-03-01 20:10 UTC, tillkruss commented
@colinleroy: Can you drop me an email via the chat bubble on https://objectcache.pro?

2022-06-26 15:49 UTC, colinleroy commented
Hi @tillkruss,

I'm sorry I've not been able to really get in touch with you yet... Life's a bit hectic. 
Do you still want to apply this PR ?

Thanks!
Colin

2022-06-28 18:41 UTC, merged

2022-06-28 18:41 UTC, tillkruss commented
@colinleroy: Yeah, this looks good.