Respect WP_REDIS_FLUSH_TIMEOUT
rhubarbgroup/redis-cache pull request #509
Opened 2024-03-06 19:08 UTC by yatsukhnenko

If set use value of `WP_REDIS_FLUSH_TIMEOUT` when flush cache
TODO: get/set timeout helpers should be added to Predis

2024-03-06 20:04 UTC, tillkruss requested changes
I think this can work, but I think we need to refactor this a little bit. We can leave `lua_flush_closure()` and all the other lua script functions as they are.

Can we add a new function, something like execute_lua_script() that will:

1. take the lua closure
2. Handle clusters and instance connections
3. Handle settings timeouts for Predis / PhpRedis

2024-03-13 16:46 UTC, yatsukhnenko commented
@tillkruss I tried to handle case when Redis cluster is used with predis and it looks like there is a lack of functionality in predis
```php
Fatal error: Uncaught Predis\NotSupportedException: Cannot use 'EVAL' with redis-cluster. in /var/www/html/wp-content/plugins/redis-cache/dependencies/predis/predis/src/Connection/Cluster/RedisCluster.php:353
```

2024-03-13 16:52 UTC, yatsukhnenko commented
Nevermind, there is no error when call `eval` directly on node

2024-03-18 19:19 UTC, tillkruss requested changes

2024-03-18 19:19 UTC, tillkruss commented on includes/object-cache.php
> +        if ( defined( 'WP_REDIS_FLUSH_TIMEOUT' ) ) {
Let's default to `5s` if `WP_REDIS_FLUSH_TIMEOUT` is not set.

2024-04-05 20:33 UTC, merged