Add filter to allow customizing who can flush the cache
rhubarbgroup/redis-cache pull request #535
Opened 2024-06-06 19:49 UTC by pmgarman

Couldn't find a CONTRIBUTING.md (i may be blind) so took a best guess. Also just assumed 2.6 but who knows?!

I think this could easily be a thing that gets enhanced deeper for multisite to allow individual site owners to flush their individual sites cache or something along those lines... but this probably serves my needs well enough :D

2024-06-06 19:56 UTC, pmgarman commented
This was the code i used to test that this worked for the author role:
```php
add_filter( 'roc_manage_redis_capability', function( $cap ) {
	return 'publish_posts';
});
```

2024-06-06 19:58 UTC, pmgarman commented
Resolved conflict in changelog

2024-06-10 17:48 UTC, tillkruss commented
Should we also make this a constant for easier access?

2024-06-10 17:53 UTC, pmgarman commented
You would only be able to define your default as a constant though right? Since the constant can't change after being filtered?

2024-06-10 18:14 UTC, tillkruss commented
> You would only be able to define your default as a constant though right? Since the constant can't change after being filtered?

Yeah, it would be set once in the `wp-config.php` and should be opt-in, not used by default.

2024-06-10 18:18 UTC, pmgarman commented
Oh I see what you mean, inverse of what I was thinking. It's monday...

I could see that being handy too yeah. I can update my PR and fix those codestyle complaints.

Any preference on your constant name?

2024-06-10 18:22 UTC, pmgarman commented
Nevermind those errors are yours :P enjoy!

2024-06-11 18:24 UTC, pmgarman commented
Opted for `WP_REDIS_MANAGER_CAPABILITY` until @tillkruss says otherwise :)

2024-06-28 18:13 UTC, tillkruss requested changes

2024-06-28 18:13 UTC, tillkruss commented on CHANGELOG.md
> +- Added `roc_manage_redis_capability` filter and `WP_REDIS_MANAGER_CAPABILITY` constant
@pmgarman: Could you add these to the README as well?

2024-07-11 15:42 UTC, pmgarman commented
@tillkruss try this on for size

2024-07-12 00:12 UTC, merged